import Head from 'next/head'
// import Image from 'next/image'
import Navbar from '../component/Navbar'
// import styles1 from "../styles/Home1.module.css";
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <style jsx>
        {`h2{
          font-size:38px
        }
        h3{
          font-size:28px
        }`}
      </style>
      <Head>
        <title>Hunter Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js'></Script> */}
      
      {/* <main className={`${styles.main} ${styles1.main}`}> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>
        <div className={styles.homeImage}>
          {/* the image tag of next cannot be used when we are using staticSideProps in prerendering  */}
          {/* <Image className={styles.myImg} src='/homeImage.jpg' alt='Coder' width={230} height={180}></Image> */}
          <img className={styles.myImg} src='/homeImage.jpg' alt='Coder' width={230} height={180}></img>
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder.
        </p>
        <div className={styles.blogs}>
          <h2>
            Popular blogs
          </h2>
          <div className={styles.blogitem}>
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript language is used to design lgoic for the web</p>
          </div>
          <div className={styles.blogitem}>
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript language is used to design lgoic for the web</p>
          </div>
          <div className={styles.blogitem}>
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript language is used to design lgoic for the web</p>
          </div>
        </div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  </>
  )
}
